apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: hello-flask
          image: jeanpcr94/hello-flask:latest
          ports:
            - containerPort: 5000
              name: microport
