apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  namespace: devops-tools
  labels:
    app: hello-flask
spec:
  ports:
    - port: 5000
      nodePort: 31000
  selector:
    app: hello-flask
  type: NodePort
